version: '3.3'

services:
  db-symfony:
    image: postgres:12
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: symfony
    ports:
        - "25432:5432"

  php-fpm-symfony:
    build:
      context: ./php-fpm
    depends_on:
      - db-symfony

    volumes:
      - ./../:/var/www
      - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  nginx-symfony:
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/certs/nginx-selfsigned.crt:/certs/server.crt
      - ./nginx/certs/nginx-selfsigned.key:/certs/server.key
      - ./nginx/certs/dhparam.pem:/certs/dhparam.pem
      - ./logs:/var/log
    depends_on:
      - php-fpm-symfony
    ports:
      - "80:80"
      - "443:443"




volumes:
  db_data:
  postgres-data:
